- name: Include tomcat7 handlers
  include: roles/tomcat7/handlers/main.yml

- name: Stat Shibboleth IdP tarball in /opt 
  stat: path=/opt/shibboleth-identity-provider-3.2.1.tar.gz
  register: shib_tarball

- name: Download Shibboleth IdP
  get_url: url={{ idp_dl_url }} dest=/opt
  when: shib_tarball.stat.exists == False

- name: Stat Shibboleth IdP source dir in /opt 
  stat: path=/opt/shibboleth-identity-provider-3.2.1
  register: shib_dir_source

- name: Unarchive Shibboleth IdP
  unarchive: src=/opt/shibboleth-identity-provider-3.2.1.tar.gz dest=/opt
  when: shib_dir_source.stat.exists == False

- name: Stat Shibboleth IdP dest dir in /opt
  stat: path=/opt/shibboleth-idp
  register: shib_dir_dest

- name: Prepare properties for Shibboleth IdP install
  template: src={{ shib_tmpls }}/shib-install.properties dest=/tmp/shib-install.properties

- name: Install Shibboleth Idp
  environment: 
    JAVA_HOME: "{{ java_home }}"
  command: |
    /opt/shibboleth-identity-provider-3.2.1/bin/install.sh \
    -Didp.sealer.password={{ idp_pw }} \
    -Didp.keystore.password={{ idp_pw }} \
    -Didp.scope={{ domain }} \
    -Didp.src.dir=/opt/shibboleth-identity-provider-3.2.1 \
    -Didp.host.name={{ idp_fqdn }} \
    -Didp.target.dir=/opt/shibboleth-idp \
    -Didp.merge.properties=/tmp/shib-install.properties
  when: shib_dir_dest.stat.exists == False

- name: tomcat7 user for idp dirs
  file: name="{{ item }}" owner=tomcat7 recurse=yes
  with_items:
    - "{{ idp_path }}/conf"
    - "{{ idp_path }}/logs"
    - "{{ idp_path }}/metadata"
    - "{{ idp_path }}/credentials"
  
- name: Install the IdP WAR
  template: src={{ shib_tmpls }}/idp.xml dest=/etc/tomcat7/Catalina/localhost/idp.xml
  notify: restart tomcat7

  
#- name: Set Tomcat conf files permission
#  file: path=/opt/tomcat/conf group=tomcat mode=g+r recurse=yes

#- name: Set Tomcat conf dir permissions
#  file: path=/opt/tomcat/conf mode=g+rwx

#- name: Set Tomcat work dirs files permission
#  file: path={{ item }} owner=tomcat recurse=yes
#  with_items:
#    - /opt/tomcat/work
#    - /opt/tomcat/temp
#    - /opt/tomcat/logs

#- name: Setup users for Tomcat manager-gui and admin-gui
#  template: src=roles/tomcat8/templates/opt/tomcat/conf/tomcat-users.xml dest=/opt/tomcat/conf/tomcat-users.xml

#- name: Set up Tomcat Upstart script
#  template: src=roles/tomcat8/templates/etc/init/tomcat8.conf dest=/etc/init/tomcat8.conf

#- name: Reload Upstart configuration
#  command: initctl reload-configuration

#- name: Start Tomcat 
#  service: name=tomcat8 state=started
