- name: Check debconf for mysql-server entries
  shell: (debconf-get-selections | grep -q -s mysql-server); echo $?
  register: debconf
  ignore_errors: yes

- name: Set debconf mysql root password
  debconf: name=mysql-server question="mysql-server/root_password" value="{{ mysql_pw }}" vtype="password"
  when: debconf.stdout == "1"
    
- name: Set debconf mysql root password again
  debconf: name=mysql-server question="mysql-server/root_password_again" value="{{ mysql_pw }}" vtype="password"
  when: debconf.stdout == "1"

- name: Install Mysql
  apt: name=mysql-server state=present

- name: Run Mysql
  service: name=mysql state=started enabled=yes

- name: Create Shibboleth Database
  shell: mysql -u root --password=password < roles/mysql/files/shibboleth.sql
